- `Numpy - Numerical Python` used: to perform large scale mathematical calcualtion
- use case : ML, Data Analysis


In [1]:
import numpy as np

In [17]:
# POWER OF NUMPY
list1 = [1, 3, 5, 7, 9]
list2 = [2, 4, 6, 8, 10]
# list1 * list2 TypeError: can't multiply sequence by non-int of type 'list'

new_list = []
for i in range(0, len(list1)):
    x = list1[i] * list2[i]
    new_list.append(x)
print(new_list)

# Using NumPy
arr1 = np.array(list1)
arr2 = np.array(list2)
arr1 * arr2

[2, 12, 30, 56, 90]


array([ 2, 12, 30, 56, 90])

`Different ways to create NumPy array`
* NumPy Array is a data structure in the NumPy Library.
* You can think of it as a `List, Dict or Tuple`

In [26]:
# 1. array: array(object, dtype=None ..)
# np.array([2,4,6,8]) #or 
np.array([2,4,6,8], dtype="int")

array([2, 4, 6, 8])

In [23]:
np.array([5.8, 9, 7, 5])
 # array() will force all elem to a single type

array([5.8, 9. , 7. , 5. ])

In [29]:
np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])

array([[9., 8., 7.],
       [6., 5., 4.]])

In [10]:
# 2. zeros & ones # default float in zeros & ones
np.zeros(5) 

array([0., 0., 0., 0., 0.])

In [44]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [39]:
np.zeros((3, 5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [47]:
np.ones((3, 4, 5), dtype=int) # ie: 3 values 4 rows and 5 cols

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [75]:
# 3. full: full(shape, fill_value, dtype=None)
np.full((2, 3), 6)

array([[6, 6, 6],
       [6, 6, 6]])

In [76]:
# 4. arange: arange(start, stop, step, dtype)
np.arange(3, 10,  dtype=float)

array([3., 4., 5., 6., 7., 8., 9.])

In [57]:
type(np.arange(3, 10,  dtype=float))

numpy.ndarray

In [34]:
# 6 eye : Returns 2D array with ones on the diagonal and zeros elsewhere
np.eye(3) 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
np.eye(3, 2, dtype='bool')

array([[ True, False],
       [False,  True],
       [False, False]])

In [38]:
# 7. linspace: create a certain number of values between two values
np.linspace(10,30,10) # start, stop, num

array([10.        , 12.22222222, 14.44444444, 16.66666667, 18.88888889,
       21.11111111, 23.33333333, 25.55555556, 27.77777778, 30.        ])

In [39]:
np.linspace(10,30,10, dtype='int')

array([10, 12, 14, 16, 18, 21, 23, 25, 27, 30])

In [44]:
# 8. random decimal: returns number between 0 and 1 
np.random.rand(5) 

array([0.24549499, 0.05569548, 0.28026329, 0.4605571 , 0.15229681])

In [43]:
np.random.rand(2, 3)

array([[0.92789679, 0.46266711, 0.64870624],
       [0.26379986, 0.33523199, 0.96110844]])

In [46]:
# 9. random decimal: returns number between 0 and 1 in normal distribution
np.random.randn(5) 

array([-0.24170951,  1.14897951, -0.42144381,  1.48017159,  0.44651153])

In [48]:
# 10. random int
np.random.randint(1, 10, (4,4)) # low high shape

array([[1, 8, 1, 3],
       [2, 4, 5, 7],
       [1, 9, 7, 4],
       [2, 6, 2, 6]])

 `Properties of NumPy: ndim shape size dtype`

In [50]:
matrix = np.random.randint(10,50,(5,4))

In [51]:
matrix

array([[49, 38, 19, 11],
       [35, 12, 17, 45],
       [13, 37, 42, 42],
       [44, 44, 26, 25],
       [34, 35, 35, 47]])

In [56]:
matrix.ndim # dimension size

2

In [54]:
matrix.shape # gives shape

(5, 4)

In [55]:
matrix.size # total no. of elem

20

In [57]:
matrix.dtype # datatype of NumPy array 

dtype('int32')