`Functions in NumPy Library`

In [10]:
import numpy as np

In [11]:
# 1. reshape
arr  = np.arange(1,16).reshape(3,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [12]:
arr.reshape(1, 15)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [24]:
# 2. max, argmax, min
arr = np.random.randint(0, 20, (4, 3))
arr

array([[ 6,  4, 15],
       [11, 16,  2],
       [14, 12, 14],
       [16,  9,  2]])

In [25]:
arr.max()

16

In [26]:
arr.argmax() # returns the index of largest element

4

In [27]:
arr.min()

2

In [28]:
arr.argmin()

5

In [38]:
# 3. concatenate: the size & dimension should be shame
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
np.concatenate([arr1, arr2])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [34]:
arr3 = np.arange(1,7).reshape(2, 3)
arr4 = np.array([[7,8,9], [10,11,12]])

In [35]:
np.concatenate([arr3, arr4])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [36]:
np.concatenate([arr3, arr4], axis=1) # axis=0 : default: means one under the other

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [50]:
# 4. split: splits 1D array into parts
arr = np.array([1, 3, 4, 50, 50, 2, 4, 6])
arr2 = np.split(arr, [3, 5]) # split from 3 index - 5 index
arr2

[array([1, 3, 4]), array([50, 50]), array([2, 4, 6])]

In [51]:
x, y, z = arr2
x

array([1, 3, 4])

In [52]:
# split in 4 equal parts 
arr = np.array([1, 3, 4, 50, 50, 2, 4, 6])
np.split(arr, 4)

[array([1, 3]), array([ 4, 50]), array([50,  2]), array([4, 6])]

In [53]:
# 4. sort
arr = np.array([3, 5, 1, 8, 6, 2, 9])
np.sort(arr)

array([1, 2, 3, 5, 6, 8, 9])

In [37]:

arr = np.array([[89,20,5,1,31], [4,3,2,7,1]])
np.sort(arr)

array([[ 1,  5, 20, 31, 89],
       [ 1,  2,  3,  4,  7]])

`Indexing, Slicing, Assigning`

In [75]:
# 1. indexing, slicing
arr = np.random.randint(5, 20, 10) # low high size
arr

array([19, 12, 12, 15,  5, 16, 11,  5,  5,  7])

In [76]:
print(arr[-2])
print(arr[4])
print(arr[4:7])
print(arr[2:-4])


5
5
[ 5 16 11]
[12 15  5 16]


In [77]:
arr = np.array([[5,10,15],
                [20,25,30],
                [35,40,45]])
arr

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [78]:
print(arr[2,2])
print(arr[-1, -3])
print(arr[0, 0:2])

45
35
[ 5 10]


In [84]:
# 2. assigning
arr = np.array([3, 4, 5, 6, 7, 8, 9])

In [87]:
arr[4] = 100
arr[0:2] = 200
arr

array([200, 200,   5,   6, 100,   8,   9])

`Comparision Operators  > < == != >= <=`

In [88]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [89]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [90]:
arr <= 4

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [94]:
(arr != 8) & (arr >= 6)

array([False, False, False, False, False,  True,  True, False,  True,
        True])

In [93]:
arr[(arr != 8) & (arr >= 6)]

array([ 6,  7,  9, 10])

`Arithmetic`

In [95]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [100]:
arr + 5

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [99]:
arr - 2

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [101]:
arr * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [102]:
arr / 10

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [103]:
arr ** 3

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [104]:
np.sqrt(100)

10.0

In [106]:
arr[arr%2 == 0]

array([ 2,  4,  6,  8, 10])

`statistical --> sum mean median min max std`

In [107]:
arr = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [108]:
np.sum(arr)

55

In [109]:
np.mean(arr) # equivalent to AVG()

5.5

In [110]:
np.median(arr)

5.5

In [111]:
np.min(arr)

1

In [112]:
np.max(arr)

10

In [116]:
np.std(arr) # std diviation

2.8722813232690143

In [117]:
np.var(arr) # variance

8.25